# Generated by Django 3.1.5 on 2021-01-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_votefact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votefact',
            old_name='voting',
            new_name='variant',
        ),
    ]
