from application.modules.index import MainView
from application.modules.vote import VotePage
from application.modules.login import LoginView
from application.modules.registration import RegistrationView
from application.modules.votings_list import VoteListView
from application.modules.edit_vote import CreateEdiVoteView
from application.modules.own_vote_list import OwnVoteListView
from application.modules.remove_vote import RemoveVotePage
from application.modules.user_list import UserList
